nginx:
    build: ./nginx/
    ports:
        - 90:90
    links:
        - php
    volumes_from:
        - app
    volumes:
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

php:
    build: ./php/
    expose:
        - 9000
    volumes_from:
        - app

app:
    image: php:5.6.24-fpm
    volumes:
        - ./app/:/var/www/html
    command: "true"

composer:
     restart: 'no'
     image: composer/composer:php7
     command: install
     volumes: 
             - ./app/:/app/



